Update shell scripts and reno config to improved system

diff --git a/rootfs/etc/s6-overlay/scripts/02-rbfeeder b/rootfs/etc/s6-overlay/scripts/02-rbfeeder
--- a/rootfs/etc/s6-overlay/scripts/02-rbfeeder
+++ b/rootfs/etc/s6-overlay/scripts/02-rbfeeder
@@ -1,5 +1,7 @@
 #!/command/with-contenv bash
-#shellcheck shell=bash disable=SC1091,SC2015
+#shellcheck shell=bash
+# shellcheck source-path=source-stubs
+# shellcheck source-path=SCRIPTDIR
 
 source /scripts/common
 s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args)
@@ -7,32 +9,32 @@ s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args)
 # Check to make sure the correct command line arguments have been set
 EXITCODE=0
 if [ -z "${LAT}" ]; then
-  "${s6wrap[@]}" echo "[ERROR] LAT environment variable not set"
-  EXITCODE=1
+    "${s6wrap[@]}" echo "[ERROR] LAT environment variable not set"
+    EXITCODE=1
 fi
 if [ -z "${LONG}" ]; then
-  "${s6wrap[@]}" echo "[ERROR] LONG environment variable not set"
-  EXITCODE=1
+    "${s6wrap[@]}" echo "[ERROR] LONG environment variable not set"
+    EXITCODE=1
 fi
 if [ -z "${BEASTHOST}" ]; then
-  "${s6wrap[@]}" echo "[ERROR] BEASTHOST environment variable not set"
-  EXITCODE=1
+    "${s6wrap[@]}" echo "[ERROR] BEASTHOST environment variable not set"
+    EXITCODE=1
 fi
 if [ -z "${ALT}" ]; then
-  "${s6wrap[@]}" echo "[ERROR] ALT environment variable not set"
-  EXITCODE=1
+    "${s6wrap[@]}" echo "[ERROR] ALT environment variable not set"
+    EXITCODE=1
 else
-  ALT="${ALT%%.*}"
+    ALT="${ALT%%.*}"
 fi
 if [ $EXITCODE -ne 0 ]; then
-  exit 1
+    exit 1
 fi
 
 # Set up timezone
 if [ -z "${TZ}" ]; then
-  "${s6wrap[@]}" echo "[WARNING] TZ environment variable not set"
+    "${s6wrap[@]}" echo "[WARNING] TZ environment variable not set"
 else
-  ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" > /etc/timezone || true
+    ln -snf "/usr/share/zoneinfo/$TZ" /etc/localtime && echo "$TZ" >/etc/timezone || true
 fi
 
 # Generate /etc/rbfeeder.ini based on environment variables
@@ -41,109 +43,108 @@ echo """
 network_mode=true
 log_file=$RBFEEDER_LOG_FILE
 debug_level=${DEBUG_LEVEL:-0}
-""" > /etc/rbfeeder.ini
+""" >/etc/rbfeeder.ini
 
 if chk_enabled "$QUIET_LOGS"; then
-  echo "disable_log=1" >> /etc/rbfeeder.ini
+    echo "disable_log=1" >>/etc/rbfeeder.ini
 fi
 
-if [ -z "${SHARING_KEY}" ]
-then
-  "${s6wrap[@]}" echo ""
-  "${s6wrap[@]}" echo "[WARNING] SHARING_KEY environment variable was not set!"
-  "${s6wrap[@]}" echo "          Please make sure you note down the key generated."
-  "${s6wrap[@]}" echo "          Pass the key as environment var SHARING_KEY on next launch!"
-  "${s6wrap[@]}" echo ""
+if [ -z "${SHARING_KEY}" ]; then
+    "${s6wrap[@]}" echo ""
+    "${s6wrap[@]}" echo "[WARNING] SHARING_KEY environment variable was not set!"
+    "${s6wrap[@]}" echo "          Please make sure you note down the key generated."
+    "${s6wrap[@]}" echo "          Pass the key as environment var SHARING_KEY on next launch!"
+    "${s6wrap[@]}" echo ""
 else
-  echo "key=$SHARING_KEY" >> /etc/rbfeeder.ini
+    echo "key=$SHARING_KEY" >>/etc/rbfeeder.ini
 fi
 
 {
-  echo "lat=$LAT"
-  echo "lon=$LONG"
-  echo "alt=$ALT"
-  echo """
+    echo "lat=$LAT"
+    echo "lon=$LONG"
+    echo "alt=$ALT"
+    echo """
 [network]
 mode=beast
   """
-  # shellcheck disable=SC2153
-  echo "external_port=$BEASTPORT"
-} >> /etc/rbfeeder.ini
+    echo "external_port=${BEASTPORT:=30005}"
+} >>/etc/rbfeeder.ini
 
 # Attempt to resolve BEASTHOST into an IP address
-if s6-dnsip4 "$BEASTHOST" > /dev/null 2>&1 ; then
-  BEASTIP=$(s6-dnsip4 "$BEASTHOST" | head -1 2> /dev/null)
-  echo "external_host=$BEASTIP" >> /etc/rbfeeder.ini
+if s6-dnsip4 "$BEASTHOST" >/dev/null 2>&1; then
+    BEASTIP=$(s6-dnsip4 "$BEASTHOST" | head -1 2>/dev/null)
+    echo "external_host=$BEASTIP" >>/etc/rbfeeder.ini
 else
-  echo "external_host=$BEASTHOST" >> /etc/rbfeeder.ini
+    echo "external_host=$BEASTHOST" >>/etc/rbfeeder.ini
 fi
 
 {
-  echo "[mlat]"
-  if chk_enabled "$ENABLE_MLAT"; then
-    if [[ -n "$MLAT_RESULTS_BEASTHOST" ]]; then
-      echo "mlat_cmd=/usr/bin/python3 /usr/local/bin/mlat-client --results beast,connect,${MLAT_RESULTS_BEASTHOST}:${MLAT_RESULTS_BEASTPORT:-30104}"
+    echo "[mlat]"
+    if chk_enabled "$ENABLE_MLAT"; then
+        if [[ -n "$MLAT_RESULTS_BEASTHOST" ]]; then
+            echo "mlat_cmd=/usr/bin/python3 /usr/local/bin/mlat-client --results beast,connect,${MLAT_RESULTS_BEASTHOST}:${MLAT_RESULTS_BEASTPORT:-30104}"
+        else
+            echo "mlat_cmd=/usr/bin/python3 /usr/local/bin/mlat-client --results beast,listen,30105 $MLAT_RESULTS_EXTRA"
+        fi
+        echo "autostart_mlat=true"
     else
-      echo "mlat_cmd=/usr/bin/python3 /usr/local/bin/mlat-client --results beast,listen,30105 $MLAT_RESULTS_EXTRA"
+        echo "autostart_mlat=false"
     fi
-    echo "autostart_mlat=true"
-  else
-    echo "autostart_mlat=false"
-  fi
-} >> /etc/rbfeeder.ini
+} >>/etc/rbfeeder.ini
 
 # If UAT_RECEIVER_HOST is set, then add UAT configuration
 if [[ -n "$UAT_RECEIVER_HOST" ]]; then
-  {
-    echo "[dump978]"
-    echo "dump978_enabled=true"
-    echo "dump978_port=30979"
-  } >> /etc/rbfeeder.ini
+    {
+        echo "[dump978]"
+        echo "dump978_enabled=true"
+        echo "dump978_port=30979"
+    } >>/etc/rbfeeder.ini
 fi
 
 # this no longer applies, rbfeeder apparently fixed it, let's make a small log entry just in case.
 if false && ! grep -qi "Serial\s*:" /proc/cpuinfo; then
-  # rbfeeder won't work without a serial number
-  "${s6wrap[@]}" echo ""
-  "${s6wrap[@]}" echo "[ERROR] Your machine doesn't have a serial number in /proc/cpuinfo"
-  "${s6wrap[@]}" echo "        You must resolve this for the container to run. Instruction to fix it can be found here:"
-  "${s6wrap[@]}" echo "        https://github.com/sdr-enthusiasts/docker-airnavradar/blob/main/version_0.4.3_workarounds.md#workaround-for-cpu-serial"
-  sleep infinity & wait $!
+    # rbfeeder won't work without a serial number
+    "${s6wrap[@]}" echo ""
+    "${s6wrap[@]}" echo "[ERROR] Your machine doesn't have a serial number in /proc/cpuinfo"
+    "${s6wrap[@]}" echo "        You must resolve this for the container to run. Instruction to fix it can be found here:"
+    "${s6wrap[@]}" echo "        https://github.com/sdr-enthusiasts/docker-airnavradar/blob/main/version_0.4.3_workarounds.md#workaround-for-cpu-serial"
+    sleep infinity &
+    wait $!
 fi
 if ! grep -qi "Serial\s*:" /proc/cpuinfo; then
-  "${s6wrap[@]}" echo "Note: no cpu serial in /proc/cpuinfo (this should no longer cause issues but log it just in case)"
+    "${s6wrap[@]}" echo "Note: no cpu serial in /proc/cpuinfo (this should no longer cause issues but log it just in case)"
 fi
 
 if [[ ! -f /sys/class/thermal/thermal_zone0/temp ]]; then
-  # rbfeeder won't work without temperature sensor
-  "${s6wrap[@]}" echo ""
-  "${s6wrap[@]}" echo "[ERROR] Your machine doesn't have a temperature sensor at /sys/class/thermal/thermal_zone0/temp"
-  "${s6wrap[@]}" echo "        You must resolve this as rbfeeder will CRASH otherwise. Instruction to fix it can be found here:"
-  "${s6wrap[@]}" echo "        https://github.com/sdr-enthusiasts/docker-airnavradar/blob/main/version_0.4.3_workarounds.md#workaround-for-temperature-sensor"
-  sleep infinity
+    # rbfeeder won't work without temperature sensor
+    "${s6wrap[@]}" echo ""
+    "${s6wrap[@]}" echo "[ERROR] Your machine doesn't have a temperature sensor at /sys/class/thermal/thermal_zone0/temp"
+    "${s6wrap[@]}" echo "        You must resolve this as rbfeeder will CRASH otherwise. Instruction to fix it can be found here:"
+    "${s6wrap[@]}" echo "        https://github.com/sdr-enthusiasts/docker-airnavradar/blob/main/version_0.4.3_workarounds.md#workaround-for-temperature-sensor"
+    sleep infinity
 fi
 
 if [[ -n "$RB_SERVER" ]]; then
 
-  # Note, the default setting in rbfeeder is rpiserver-ng.rb24.com, which resolves to the 6 IP addresses below.
-  # As of 22-Nov-2023, the following IP addresses are known to work: 79.133.49.85 (Frankfurt server) 23.29.123.254 (Austin, TX US server)
-  # The following IP addresses are known NOT to work: 46.21.149.109 23.29.123.240 46.21.149.110 79.133.49.90
+    # Note, the default setting in rbfeeder is rpiserver-ng.rb24.com, which resolves to the 6 IP addresses below.
+    # As of 22-Nov-2023, the following IP addresses are known to work: 79.133.49.85 (Frankfurt server) 23.29.123.254 (Austin, TX US server)
+    # The following IP addresses are known NOT to work: 46.21.149.109 23.29.123.240 46.21.149.110 79.133.49.90
 
-  if chk_enabled "$RB_SERVER"; then
-    tz_offset="$(date +%:::z | sed 's/^\+//;s/^0//;s/^-0/-/')"
-    if (( $(bc -l <<< "$tz_offset < -2") )); then
-      # Timezone is in the Western Hemisphere - use the US server IP
-      RB_SERVER="23.29.123.254"
-    else
-      # Timezone is in the Eastern Hemisphere - use the EU server IP
-      RB_SERVER="79.133.49.85"
+    if chk_enabled "$RB_SERVER"; then
+        tz_offset="$(date +%:::z | sed 's/^\+//;s/^0//;s/^-0/-/')"
+        if (($(bc -l <<<"$tz_offset < -2"))); then
+            # Timezone is in the Western Hemisphere - use the US server IP
+            RB_SERVER="23.29.123.254"
+        else
+            # Timezone is in the Eastern Hemisphere - use the EU server IP
+            RB_SERVER="79.133.49.85"
+        fi
     fi
-  fi
-  {
-    echo ""
-    echo "[server]"
-    echo "a_host=${RB_SERVER}"
-  }  >> /etc/rbfeeder.ini
+    {
+        echo ""
+        echo "[server]"
+        echo "a_host=${RB_SERVER}"
+    } >>/etc/rbfeeder.ini
 fi
 
 # Create log dirs
